# Copyright (c) 2022 - 2023 MDSANIMA

# This file is for building and deploying documentation site to GitHub Pages.


name: docs-build-deployment
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Sphinx Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install development dependencies
        run: pip install ".[dev]"
      - name: Install documentation dependencies
        run: pip install ".[doc]"
      - name: Build mdsanima-dev package
        run: python -m build
      - name: Install mdsanima-dev package
        run: pip install dist/mdsanima_dev-*-py3-none-any.whl
      - name: Build Sphinx documentation site
        run: sphinx-build -M dirhtml docs build
      - name: Create CNAME for custom domain
        run: cp CNAME ./build/dirhtml/
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dirhtml/
