# Copyritht © 2022-2023 Marcin Różewski MDSANIMA

name: docs-build-deployment
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Sphinx Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements-*.txt"
      - name: Install DEVS Dependencies
        run: pip install -r requirements-dev.txt
      - name: Install DOCS Dependencies
        run: pip install -r requirements-doc.txt
      - name: Build Package
        run: python -m build
      - name: Install Package
        run: pip install dist/mdsanima_dev-*-py3-none-any.whl
      - name: Build Documentation
        run: python setup.py build_sphinx
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dirhtml/
