name: docs-build-deployment
on:
  push:
    branches: [main]

jobs:
  docs:
    name: documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "**/requirements-dev.txt"
      - name: install dependencies
        run: pip install -r docs/requirements-dev.txt
      - name: build package
        run: python setup.py sdist bdist_wheel
      - name: install package
        run: pip install dist/mdsanima_dev-*-py3-none-any.whl
      - name: build documentation
        run: python setup.py build_sphinx
      - name: upload to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dirhtml/
